name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-ruby@v1
      with:
        node-version: 16.x
    - name: Install dependencies
      run: npm install
    - name: Build Eleventy
      run: npm run build
    - name: Commit and push generated site
      run: |
        git config --global user.email "build-bot@example.com"
        git config --global user.name "build-bot"
        git add --all
        git commit -m "Build" || exit 0
        git push origin main:build --force
